package com.dev.msscbeerorderseervice.domain;

public enum BeerOrderStatusEnum {
    NEW,VALIDATED,VALIDATION_PENDING,VALIDATION_EXCEPTION,ALLOCATION_PENDING,ALLOCATED,ALLOCATION_EXEPTION,
    PENDING_INVENTORY,PICKED_UP,DELIVERED,DELIVERY_EXCEPTION

}
